apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: orders-pr-project
  namespace: openshift-gitops
spec:
  description: "Project for PR demo"
  sourceRepos:
    - 'https://github.com/too-common-name/gitops-experiments-orders.git'
  destinations:
    - namespace: 'orders-pr-*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace