apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bookinfo-project
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Project for the Bookinfo application deployed from Quay OCI"

  sourceRepos:
    - 'quay.io/rh-ee-drossi'

  destinations:
    - namespace: 'bookinfo'
      server: '*'

  namespaceResourceWhitelist:
    - group: 'gateway.networking.k8s.io'
      kind: Gateway
    - group: 'gateway.networking.k8s.io'
      kind: HTTPRoute
    - group: 'route.openshift.io'
      kind: Route

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
