apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bookinfo-project
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Project for the Bookinfo application deployed from Quay OCI"

  sourceRepos:
    - 'oci://quay.io/rh-ee-drossi/bookinfo'

  destinations:
    - namespace: 'bookinfo'
      server: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
