apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: ecommerce-stage

commonLabels:
  environment: stage
  tenant: ecommerce

patches:
  - path: patch-quota.yaml
