apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: invoices-project
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  description: "Project for the Invoice team (Kustomize)"
  
  # 1. Where can I pull the code from?
  sourceRepos:
  - 'https://github.com/too-common-name/gitops-experiments-invoices'

  # 2. Where can I deploy?
  destinations:
  - namespace: ecommerce-qa
    server: '*'
  - namespace: ecommerce-stage
    server: '*'
  - namespace: ecommerce-prod
    server: '*'

  # 3. RBAC: Who can do what?
  roles:
  - name: team-invoices-deployer
    description: "Sync permissions for the Invoices team"
    policies:
    # p = policy, subject, resource, action, target, effect
    - p, proj:invoices-project:team-invoices-deployer, applications, get, invoices-project/*, allow
    - p, proj:invoices-project:team-invoices-deployer, applications, sync, invoices-project/*, allow
    groups:
    - ocp_team_invoices # Mapped to the OpenShift/SSO group