apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: orders-pr-demo
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  generators:
    - pullRequest:
        github:
          owner: too-common-name
          repo: gitops-experiments-orders
        requeueAfterSeconds: 20
      filters:
      - branchMatch: ".*-argocd"
  template:
    metadata:
      name: 'orders-pr-{{number}}'
    spec:
      project: orders-pr-project 
      source:
        repoURL: 'https://github.com/too-common-name/gitops-experiments-orders.git'
        targetRevision: '{{head_sha}}'
        path: apps/orders
        helm:
          valueFiles:
            - values-qa.yaml
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'ecommerce-pr-{{number}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true