apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: invoices-appset
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
  - git:
      repoURL: 'https://github.com/too-common-name/gitops-experiments-invoices'
      revision: HEAD
      directories:
      - path: 'apps/invoices/overlays/*'
  template:
    metadata:
      name: 'invoices-{{path.basename}}' 
    spec:
      project: invoices-project 
      source:
        repoURL: 'https://github.com/too-common-name/gitops-experiments-invoices'
        targetRevision: HEAD
        path: '{{path}}' 
      destination:
        server: https://kubernetes.default.svc
        namespace: 'ecommerce-{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true