apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: orders-appset
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
  - list:
      elements:
      - env: qa
      - env: stage
      - env: prod
  template:
    metadata:
      name: 'orders-{{env}}'
    spec:
      project: orders-project
      source:
        repoURL: 'https://github.com/too-common-name/gitops-experiments-orders'
        targetRevision: HEAD
        path: apps/orders
        helm:
          valueFiles: 
          - values-{{env}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: 'ecommerce-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true