apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: invoices-prod
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: prod-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: 'invoices-prod-{{name}}' 
    spec:
      project: invoices-project
      source:
        repoURL: 'https://github.com/too-common-name/gitops-experiments-invoices'
        targetRevision: HEAD
        path: 'apps/invoices/overlays/prod'
      destination:
        server: '{{server}}'
        namespace: 'ecommerce-prod'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true