apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants-prod
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: prod-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: 'tenant-prod-{{name}}'
    spec:
      project: ecommerce-platform-project
      source:
        repoURL: 'https://github.com/too-common-name/gitops-experiments-platform'
        targetRevision: HEAD
        path: 'platform/tenants/overlays/prod'
      destination:
        server: '{{server}}'
        namespace: 'ecommerce-prod'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true