apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: argodemo
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  argoServer:
    argoNamespace: openshift-gitops
  placementRef:
    name: argodemo-placement
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: default
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  clusterSet: default
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: argodemo-placement
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  clusterSets:
    - default
