apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: invoices-nonprod
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
    - matrix:
        generators:
          - clusterDecisionResource:
              configMapRef: acm-placement
              labelSelector:
                matchLabels:
                  cluster.open-cluster-management.io/placement: nonprod-placement
              requeueAfterSeconds: 180
          - list:
              elements:
                - env: qa
                - env: stage
  template:
    metadata:
      name: 'invoices-{{env}}-{{name}}'
    spec:
      project: invoices-project
      source:
        repoURL: 'https://github.com/too-common-name/gitops-experiments-invoices'
        targetRevision: HEAD
        path: 'apps/invoices/overlays/{{env}}'
      destination:
        server: '{{server}}'
        namespace: 'ecommerce-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
