apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: orders-prod
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: prod-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: 'orders-prod-{{name}}' 
    spec:
      project: orders-project
      source:
        repoURL: 'https://github.com/too-common-name/gitops-experiments-orders'
        targetRevision: HEAD
        path: apps/orders
        helm:
          valueFiles:
            - values-prod.yaml
      destination:
        server: '{{server}}'
        namespace: ecommerce-prod
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
